apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      initContainers:
      - name: init-apache
        image: custom-nextcloud:latest
        command: ["/bin/sh", "-c"]
        args:
          - >
            echo "ServerName localhost" > /etc/apache2/conf-available/server-name.conf &&
            a2enconf server-name
        volumeMounts:
        - name: apache-config
          mountPath: /etc/apache2/conf-available
      containers:
      - name: nextcloud-container
        image: custom-nextcloud:latest
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 128Mi
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        envFrom:
        - configMapRef:
            name: nextcloud-configmap
        - secretRef:
            name: nextcloud-secret
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /index.php
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /index.php
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: apache-config
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-service
  labels:
    app: nextcloud
spec:
  selector:
    app: nextcloud
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
